### ISSUE TITLE
계정을 연결하고 나면 Nextcloud 로 표시되는 버그

### ISSUE THREAD

**Issue by chaeya** [hamonikr/hamonikr-drive#1]
계정연결 전 화면에서는 의도한 대로 `하모니카 클라우드`로 표시되지만
연결 후 나오는 메세지는 Nextcloud 로 표기 됨.

gnome-online-accout 에서 직접 표시하는 부분을 수정해야 할 것 같음.
![온라인 계정_023](https://user-images.githubusercontent.com/405502/115670012-e8666500-a383-11eb-99fe-015307a02fae.png)

**Comment by igothere** [comment]
확인중 입니다.

**Comment by chaeya** [comment]
시스템 재시작하면 문제 해결됨.
